version: "3"

services:
  doc-store-api:
    image: stoplight/prism:3.2.2
    volumes:
      - ${PWD}/../openapi-spec/doc-store-api.yml:/opt/api/doc-store-api.yml:ro
    command: mock -h doc-store-api /opt/api/doc-store-api.yml
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.25.0
    environment:
      API_URL: http://localhost:${API_PORT}/swagger-ui/doc-store-api.yml
    volumes:
      - ${PWD}/../openapi-spec/doc-store-api.yml:/usr/share/nginx/html/doc-store-api.yml:ro
      - ${PWD}/../api-docs:/usr/share/nginx/html/api-docs
  reverse-proxy:
    image: nginx:1.17.1-alpine
    ports:
      - ${API_PORT}:8080
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
